---
- name: create users and files/dir in user home dir
  hosts: all
  tasks:
    - name: Create users
      user:
        name: "{{a}}"
        password: "{{b}}"
        home: "{{c}}"
    - name: create files/dir 
      file:
        name: "{{d}}"
        state: "{{e}}"
...
