---
- name: Implementing handlers
  hosts: all
  tasks:
    - name: Install apache2
      apt:
        name: apache2
        state: present
        update_cache: yes
      notify: restart apache2
    - name: edit the index.html
      copy:
        content: "welcome to MYINTELLIQ"
        dest: /var/www/html/index.html
      notify: restart apache2
  handlers:
    - name: restart apache2
      service:
        name: apache2
        state: restarted
    - name: check urls
      uri:
        url: "{{item}}"
        status_code: 200
      with_items:
        - http://172.31.87.203
        - http://172.31.86.116
...
