---
- name: Implementing playscope variables
  hosts: appserver
  vars:
    - a: tomcat10
    - b: present
    - c: yes
  tasks:
    - name: Install s/w application
      apt:
       name: "{{a}}"
       state: "{{b}}"
       update_cache: "{{c}}"
...
