---
- name: install git on ubuntu
  hosts: ubuntu
  tasks:
    - name: install git
      apt:
        name: git
        state: present
        update_cache: yes
- name: install git on redhat
  hosts: redhat
  tasks:
    - name: install git
      yum:
        name: git
        state: present
        update_cache: yes
...
