---
- name: Configurng tomcat10 using loops
  hosts: all
  tasks:
    - name: install tomcat10 and tomcat10-admin
      apt:
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items:
        - {a: tomcat10,b: present,c: yes}
        - {a: tomcat10-admin,b: present,c: yes}
    - name: copy tomcat-users.xml file
      copy:
        src: tomcat-users.xml
        dest: /etc/tomcat10
    - name: change name of tomcat from 8080 to 9090
      replace:
        regexp: 8080
        replace: 9090
        path: /etc/tomcat10/server.xml
    - name: restart tomcat
      service:
        name: tomcat10
        state: restarted
    - name: pause for 1 min
      pause:
        minutes: 1
    - name: check tomcat response all servers
      uri:
        url: "{{item}}"
        status_code: 200
      with_items:
        - http://172.31.86.116
        - http://172.31.87.203

...
