---
- name: configure apache / httpd on all servers
  hosts: all
  tasks:
    - block:
      - name: install apache2 using apt
        apt:
          name: apache2
          state: present
          update_cache: yes
      rescue:
        - name: install httpd using yum
          yum:
            name: httpd
            state: present
            update_cache: yes
    - name: edit index.html file
      copy:
        content: "Sushmitha"
        dest: /var/www/html/index.html
    - block:
      - name: restart apache2
        service:
          name: apache2
          state: restarted
      rescue:
        - name: restart httpd
          service:
            name: httpd
            state: restarted
    - name: check apache2/htppd response on all servers
      uri:
        url: "{{item}}"
        status_code: 200
      with_items:
        - http://172.31.86.116
        - http://172.31.87.203
        - http://172.31.93.203
...
