---
- name: install git on all servers based on os
  hosts: all
  tasks:
    - name: install git on ubuntu using apt module
      apt:
        name: git
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
    - name: install git on rhel using yum module
      yum:
        name: git
        state: present
        update_cache: yes
      when: ansible_distribution == "RedHat"
